### PR TITLE
fix/additional-nonces-checks (PR 7)

### LINKED ISSUE #411: Not all accounts' nonces are sync before execution
Before starting to execute a module we run [`getNonceSyncMessages`](https://github.com/NomicFoundation/ignition/blob/316ec19b1df431a665e523cefd88ef4db7f0bf31/packages/core/src/new-api/internal/new-execution/nonce-management.ts#L42C23-L42C43) to sync the nonces from the previous with the actual ones, and to prevent us from execution if there are user transactions without enough confirmations.

We only check the accounts that we have already used, but we have to check every transaction that's either a `from` in a future, or the default sender.

### PR DESCRIPTION
**Pull request by kanej**
Include the future senders from the module when syncing nonces for checks. 

The senders for all futures without exStates that will be used if the module executes, are now added to the syncing taking into account usage of default sender when `from` is undefined.

Resolves #411

### CODE REVIEW

File: packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts [hunk 1]
```diff
@@ -279,3 +242,43 @@ function createMapFromSenderToNonceAndTransactions(
...
+function _resolveFutureSenders(
+  ignitionModule: IgnitionModule<string, string, IgnitionModuleResult<string>>,
+  accounts: string[],
+  defaultSender: string,
+  exStateIds: string[]
+): string[] {
+  const futures = getFuturesFromModule(ignitionModule);
+
+  const senders: string[] = futures
+    .filter((f) => !exStateIds.includes(f.id))
```
Comment (kanej) [inline packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts:259]: Exclude existing exStates. They get dealt with by a different path.

File: packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts [hunk 2]
```diff
@@ -279,3 +242,43 @@ function createMapFromSenderToNonceAndTransactions(
...
+
+  return uniq(senders);
+}
+
+function _pickFrom(
+  future: Future,
+  accounts: string[],
+  defaultSender: string
+): string | null {
+  if (isNamedContractAtFuture(future)) {
```
Comment (kanej) [inline packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts:271]: I took this pattern as opposed to a sophisticated filter higher up as it gives nicer typing under conditions where we change futures that breaks the `f.from` here.

File: packages/core/src/type-guards.ts [hunk 3]
```diff
@@ -170,7 +170,7 @@ export function isNamedStaticCallFuture(
  */
 export function isReadEventArgumentFuture(
   future: Future
-): future is StaticCallFuture<string, string> {
+): future is ReadEventArgumentFuture {
```
Comment (kanej) [inline packages/core/src/type-guards.ts:173]: I assume this has just never been used.

**Review by alcuadrado — APPROVED** [review]
