### PR TITLE
Catch base fee error and rethrow as ignition error

### LINKED ISSUE #594: Fix error output for fee exceeding block gas limit
Error output when `initialBaseFeePerGas` in hardhat config is greater than the `blockGasLimit` is an ugly stack trace.

- [ ] Add a validation to check for this case
- [ ] Add a new validation error to ensure the output looks good

### PR DESCRIPTION
**Pull request by zoeyTM**
fixes #594 

screenshot (with redacted file system info in stack trace):

Screen Shot 2023-10-31 at 11 28 30 AM

### CODE REVIEW

**Comment by kanej** [comment]
Can you add a set of reproduction steps so I can test the error?

**Comment by zoeyTM** [comment]
@kanej 

Steps to reproduce:

1. set the `hardhat.config.js` of an example to:
```
hardhat: {
      mining: {
        auto: false,
      },
      blockGasLimit: 1,
      initialBaseFeePerGas: 1_000_000_000,
    },
```
2. run `npx hardhat node`
3. deploy the example module with `--network localhost`

File: packages/core/src/errors-list.ts [hunk 1]
```diff
@@ -169,6 +169,11 @@ export const ERRORS = {
       message:
         "The next nonce for %sender% should be %expectedNonce%, but is %pendingCount%. Please make sure not to send transactions from %sender% while running this deployment and try again.",
     },
+    BASE_FEE_EXCEEDS_GAS_LIMIT: {
```
Comment (kanej) [inline packages/core/src/errors-list.ts:172]: What do you think of adding it to the whitelist. Based on the rules I think it can be argued either way, but I suspect the stacktrace just isn't useful in this context.

**Review by kanej — COMMENTED** [review]
Lets add an integration test for this.

File: packages/core/src/errors-list.ts (hunk 1 above)
Comment (zoeyTM) [reply packages/core/src/errors-list.ts:172]: I'm on board with that idea

**Review by kanej — APPROVED** [review]
Looks good. Lets get this **squash** merged!
